version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - ${MEDIA}/Duplicati/config:/config
      - ${MEDIA}/Duplicati/backups:/backups
      - ${MEDIA}/Sync:/source
    ports:
      - 8200:8200
    restart: unless-stopped